# Generated by Django 4.2.10 on 2024-04-25 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                (
                    "slug",
                    models.SlugField(max_length=250, unique_for_date="publicacion"),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("cantidad", models.IntegerField()),
                (
                    "publicacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="fecha de publicación",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de modificación"
                    ),
                ),
            ],
        ),
    ]
